title: Pengeluar Pelekat Jenama Dunia
home: Laman Utama
products: Produk
about_us: Tentang Kami
articles: Artikel
contact: Hubungi
slide1_h1: Mesra Alam
slide1_p: Sijil label hijau untuk ketoksikan rendah dan pelepasan formaldehid yang rendah. Dapatkan mata BCA Green Mark dengan pelekat kami.
slide2_h1: Lantai
slide2_p: Pelekat untuk semua aplikasi lantai. Lantai kayu keras dan vinil, karpet dan jubin.
slide3_h1: Pertukangan Kayu Umum
slide3_p: Pelekat untuk pembuatan perabot.
slide4_h1: Eksport Global
slide4_p: Hubungi kami untuk menjadi pengedar. Kami menghantar produk kami ke seluruh dunia.
pitch1_h3: ISO 14001
pitch1: Pelekat kami memenuhi piawaian kualiti antarabangsa.
pitch2_h3: Mesra Alam
pitch2: Pelekat yang diperakui label hijau untuk ketoksikan rendah dan pelepasan formaldehid yang rendah.
pitch3_h3: Tahan Lama
pitch3: Ikatan kuat yang tahan lama.
pitch4_h3: Global
pitch4: Kami mengeksport pelekat kami ke seluruh dunia.
references_h6: Projek yang menggunakan produk kami.
company: Syarikat
company_p1: Kami adalah pengeluar dan pengedar pelekat terkemuka di Asia Tenggara, beribu pejabat di Singapura. Ditubuhkan pada tahun 1972, syarikat ini diperakui ISO 14001, menunjukkan penekanan yang kami berikan pada R&D, kualiti produk, dan perkhidmatan pelanggan yang prihatin.
company_p2: Produk kami digunakan secara meluas dalam pelbagai industri, terutama dalam projek pembinaan di Lapangan Terbang Antarabangsa Changi, Marina Bay, dan Sentosa Integrated Resorts.

