lang_name: 'Bahasa Melayu'
title: 'Pengeluar Pelekat Jenama Dunia'
home: 'Laman Utama'
products: 'Produk'
about_us: 'Tentang Kami'
articles: 'Artikel'
contact: 'Hubungi Kami'
slide1_h1: 'Mesra Alam'
slide1_p: 'Pensijilan label hijau untuk bebas formaldehid, toksik rendah dan pelepasan rendah. Dapatkan mata Green Mark BCA dengan pelekat kami.'
slide2_h1: 'Lantai'
slide2_p: 'Pelekat untuk semua aplikasi lantai. Lantai kayu keras dan vinil, permaidani dan jubin.'
slide3_h1: 'Pertukangan Kayu Umum'
slide3_p: 'Pelekat untuk pembuatan perabot.'
slide4_h1: 'Eksport Secara Global'
slide4_p: 'Hubungi kami untuk menjadi pengedar. Kami menghantar produk kami ke seluruh dunia.'
pitch1_h3: ISO Bertauliah
pitch1: Pelekat kami mendapat pensijilan ISO 14001, ISO 45001 dan ISO 9001.
pitch2_h3: 'Eco-Friendly'
pitch2: 'Pensijilan label hijau untuk bebas formaldehid, toksik rendah dan pelepasan rendah.'
pitch3_h3: 'Tahan Lama'
pitch3: 'Ikatan kuat yang tahan lama.'
pitch4_h3: 'Global'
pitch4: 'Kami mengeksport pelekat kami ke seluruh dunia.'
references_h6: 'Projek yang menggunakan produk kami.'
company: 'Syarikat'
company_p1: "Kami merupakan pengeluar dan pengedar utama pelekat mesra alam serta bebas formaldehid di Asia Tenggara, beribu pejabat di Singapura. Ditubuhkan pada tahun 1972, syarikat kami diperakui ISO 14001, mencerminkan komitmen kami terhadap amalan lestari, penyelidikan & pembangunan berterusan, kualiti produk, dan layanan pelanggan yang prihatin."
company_p2: "Dengan kehadiran kukuh di Malaysia, termasuk lokasi strategik dari Johor ke Kuala Lumpur (KL) dan Pulau Pinang, kami menawarkan formulasi hijau yang memenuhi tuntutan industri sambil mengurangkan impak terhadap alam sekitar dan kesihatan. Penyelesaian pelekat kami dipercayai merentas sektor—khususnya digunakan dalam projek-projek utama seperti Lapangan Terbang Antarabangsa Changi, Marina Bay, dan Resorts World Sentosa."
singapore: 'Singapura'
malaysia: 'Malaysia'
email: E-mel
phone: Telefon
fax: Faks
no_articles: Tiada artikel tersedia lagi.
back_to_articles: Kembali ke Artikel
distributor_title: Jadi Pengedar
distributor_partner_title: Rakan Kongsi dengan Pelekat Jenama Dunia
distributor_partner_description: Sertai rangkaian global pengedar yang dipercayai dan bawa pelekat berprestasi tinggi ke pasaran anda.
distributor_apply_now: Mohon Sekarang
distributor_why_partner: Mengapa Rakan Kongsi Dengan Kami
distributor_reliable_quality_title: Kualiti Boleh Dipercayai
distributor_reliable_quality_description: Disokong oleh pengalaman berdekad-dekad dalam pembuatan pelekat dan inovasi produk yang berterusan.
distributor_eco_title: Formulasi Mesra Alam
distributor_eco_description: Kami menawarkan pelekat bebas formaldehid dan larutan berasaskan pelarut mesra alam yang kering dengan cepat sambil memenuhi piawaian keselamatan global.
distributor_brand_title: Sokongan Jenama & Teknikal
distributor_brand_description: Dapatkan akses kepada alat pemasaran, latihan teknikal, helaian data keselamatan dan bimbingan daripada pakar produk kami.
distributor_attractive_margins_title: Margin Menarik
distributor_attractive_margins_description: Kami menyediakan struktur harga yang kompetitif dan program pengedar yang disesuaikan dengan pasaran anda.
distributor_apply_title: Mohon untuk Menjadi Pengedar
distributor_apply_description: Sila isi borang di bawah. Kami akan menghubungi anda dalam masa 5 hari perniagaan.
distributor_company_name: Nama Syarikat
distributor_contact_name: Nama Orang Hubungan
distributor_website_url: URL Laman Web
distributor_job_title: Jawatan
distributor_city_region: Bandar / Wilayah
distributor_phone_number: Nombor Telefon
distributor_industries: Industri atau segmen pasaran?
distributor_product_categories: Kategori produk
distributor_water_based: Pelekat Berasaskan Air
distributor_formaldehyde_free: Pelekat Bebas Formaldehid
distributor_eco_friendly: Pelekat Mesra Alam
distributor_construction: Pelekat Pembinaan
distributor_others: Lain-lain
distributor_interest: Minat atau komen anda
distributor_submit: Hantar Permohonan