available_in: "Tersedia dalam"
technical_specification: "Spesifikasi Teknikal"
msds: "Lembaran Data Keselamatan Bahan"
products_200_description: "Pelekat kontak untuk busa poliuretana & permaidani."
products_300_description: "Pelekat kontak untuk getah, logam, kayu, kulit, plastik, papan keras & lain-lain."
products_3000_description: "Getah sintetik berkualiti. Sangat kuat, fleksibel, kalis air dan tahan bahan kimia. Akan melekat pada permukaan semula jadi seperti kayu dan getah. Juga akan melekat pada kulit tiruan, kain getah, logam berkilat, seramik, papan keras, linoleum, plastik keras & konkrit."
products_3008-pva_description: "Pelekat berasaskan air yang cepat kering untuk pertukangan kayu umum."
products_3009-pva_description: "Pelekat berasaskan air untuk lantai parket."
products_3013_description: "Pelekat berasaskan air untuk permukaan yang sukar."
products_303-superglue_description: "Pelekat cyanoacrylate untuk logam, plastik, getah & lain-lain."
products_303-vinyl-tile_description: "Pelekat untuk lantai vinil."
products_313-pva_description: "Pelekat berasaskan air untuk pertukangan kayu umum."
products_323-pva_description: "Pelekat berasaskan air untuk kegunaan umum."
products_500_description: "Pelekat kontak untuk kanvas, getah, logam, kulit, plastik, kayu, papan keras & lain-lain."
products_600_description: "Pelekat semburan tidak mudah terbakar untuk getah, logam, papan lapis, kulit, plastik, buih kuning, aluminium & lain-lain."
products_606-vinyl-tile_description: "Pelekat untuk lantai vinil, penutup dinding & karpet bersokongan PVC."
products_800_description: "Pelekat semburan dengan kelikatan sederhana untuk busa poliuretana, gentian kaca & kayu."
products_808_description: "Getah sintetik berkualiti. Fleksibel, kalis air dan tahan bahan kimia. Sesuai digunakan dengan kulit tiruan, bahan poromerik, kain, getah yang divulkanisir, kayu, logam kaca, seramik, papan keras, linoleum, konkrit dan plastik keras."
products_8830_description: "Pelekat kontak busa Polistirena tanpa bau."
products_909_description: "Pelekat sensitif tekanan untuk melekatkan kebanyakan jenis tekstil & jubin karpet bersokongan PVC."
products_acetic-silicone-sealants_description: "Silikon untuk kaca umum dan pelbagai tujuan DIY."
products_acrylic-sealants_description: "Sealant akrilik untuk kaca umum & pelbagai aplikasi DIY."
products_E-100_description: "Pelekat untuk getah, logam, kayu, kulit, plastik, papan keras. Ia sesuai digunakan dalam perabot, hiasan dalaman, kulit. industri penghawa dingin dan pembuatan kasut."
products_g-spray_description: "Pelekat semburan tahan panas untuk busa poliuretana, gentian kaca & kayu."
products_high-g-spray_description: "Pelekat semburan tahan panas untuk busa poliuretana, gentian kaca & kayu."
products_PVC-solvent-cement_description: "Pelekat untuk paip PVC, kelengkapan, paip air dan industri lain-lain."
products_world-bond_description: "Pelekat kontak yang boleh diguna untuk melekatkan pelbagai jenis bahan binaan."

