title: World Brand Adhesive Manufacturer
home: Home
products: Products
about_us: About Us
articles: Articles
contact: Contact
slide1_h1: Eco-Friendly
slide1_p: Green label certification for low toxicity and low formaldehyde emissions. Earn BCA Green Mark points with our adhesives.
slide2_h1: Flooring
slide2_p: Adhesive for all flooring applications. Hardwood and vinyl floors, carpet and tiles.
slide3_h1: General Woodworking
slide3_p: Adhesive for furniture making.
slide4_h1: Export Globally
slide4_p: Contact us to be a distributor. We ship our products world wide.
pitch1_h3: ISO 14001
pitch1: Our adhesives meet international quality standards.
pitch2_h3: Eco-Friendly
pitch2: Green label certified adhesives for low toxicity and low formaldehyde emissions.
pitch3_h3: Durable
pitch3: Strong bonds that last.
pitch4_h3: Global
pitch4: We export our adhesives all over the world.
references_h6: Projects utilizing our products.

