available_in: Available in
technical_specification: Technical Specification
msds: Material Safety Data Sheet
products_170_description: A quality, super strong rubber formulation, specially for sofa making purposes. Flexible, waterproof, chemical resistance, and formaldehyde-free. Will bond almost anything (natural & synthetic leathers, fabrics, mattress partition).
products_200_description: Contact adhesive for polyurethane foam & carpet.
products_300_description: Contact Adhesive for rubber, metal, wood, leather, plastics, hardboard & etc.
products_301_description: A high-quality, synthetic rubber adhesive that is super strong, flexible, waterproof, chemical-resistant and Formaldehyde free. Bonds a variety of materials including natural and simulated leathers, poromeric materials, fabrics, vulcanized rubber, wood, glass, metals, ceramics, hardboards, linoleum, most rigid plastics, and concrete.
products_3000_description: A quality synthetic rubber. Super strong, flexible, water-proof and chemical resistant. Will bond to natural surfaces like wood and rubber. Will also adhere to artificial leathers, rubberized fabrics, glassy metals, ceramics, hardboards, linoleum, rigid plastics & concrete.
products_3008-pva_description: Fast drying water-based adhesive for general woodworking.
products_3009-pva_description: Water-based adhesive for parquet flooring.
products_3013_description: Water-based adhesive for difficult surfaces.
products_303-superglue_description: Cyanoacrylate adhesive for metal, plastic, rubber & etc.
products_303-vinyl-tile_description: Adhesive for vinyl flooring.
products_313-pva_description: Water-based adhesive for general woodworking.
products_323-pva_description: Water-based adhesive for general purposes.
products_500_description: Contact adhesive for canvas, rubber, metal, leather, plastics, wood, hardboard & etc.
products_600_description: Spray adhesive non-flammable for rubber, metal, plywood, leather, plastics, yellow foam, aluminium & etc.
products_606-vinyl-tile_description: Adhesive for vinyl flooring, wall coverings & PVC backed carpet.
products_800_description: Spray adhesive medium viscosity for polyurethane foam, fibre glass & wood
products_808_description: A quality synthetic rubber. Flexible water-proof and chemical resistant. Good for use with simulated leathers, poromeric material, fabrics, vulanized rubber, wood, glass metals, ceramics, hardboards, linoleum, concrete and rigid plastics.
products_888_description: Contact Adhesive for rubber, metal, wood, leather, plastics, hardboard & etc.
products_8830_description: Odourless Polystyrene Foam Contact Adhesive.
products_909_description: Pressure sensitive adhesive for bonding most types of textile & PVC backed carpet tiles.
products_acetic-silicone-sealants_description: Silicone for general glazing and various DIY purposes.
products_acrylic-sealants_description: Acrylic sealant for general glazing & various DIY applications.
products_E-100_description: Adhesive for rubber, metal, wood, leather, plastics, hardboard. It is suitable for use in the furniture, interior decoration, leather. air-conditioning and shoe-making industries.
products_g-spray_description: Spray adhesive heat resistant for polyurethane foam, fibre glass & wood.
products_high-g-spray_description: Heat resistant spray adhesive for polyurethane foam, fibre glass & wood.
products_PVC-solvent-cement_description: Adhesive for PVC pipes, fittings, water pipes and ETC industries.
products_world-bond_description: A gunnable contact adhesive for bonding a wide variety of construction materials.
