lang_name: '中文'
title: '地球牌粘合剂制造商'
home: '首页'
products: '产品'
about_us: '关于我们'
articles: '文章'
contact: '联系我们'
slide1_h1: '环保'
slide1_p: '获得绿色标签认证，确保无甲醛、低毒性和低排放。使用我们的胶粘剂可以获得BCA绿色标志积分。'
slide2_h1: '地板'
slide2_p: '适用于所有地板应用的粘合剂。硬木和乙烯基地板、地毯和瓷砖。'
slide3_h1: '一般木工'
slide3_p: '适用于家具制作的粘合剂。'
slide4_h1: '全球出口'
slide4_p: '联系我们成为经销商。我们将产品运送到全球各地。'
pitch1_h3: ISO 认证
pitch1: 我们的粘合剂通过了 ISO 14001、ISO 45001 和 ISO 9001 认证。
pitch2_h3: '环保'
pitch2: '获得绿色标签认证，确保无甲醛、低毒性和低排放。'
pitch3_h3: '耐用'
pitch3: '持久的强力粘合。'
pitch4_h3: '全球'
pitch4: '我们将粘合剂出口到全球各地。'
references_h6: '使用我们产品的项目。'
company: '公司'
company_p1: '我们是东南亚领先的粘合剂制造商和分销商，总部设在新加坡。公司成立于1972年，已通过ISO 14001认证，展示了我们对研发、产品质量和细致客户服务的重视。我们在马来西亚拥有强大的业务存在，涵盖从柔佛到吉隆坡 (KL) 及槟城的主要地点。'
company_p2: '我们的产品广泛应用于各种行业，尤其是在樟宜国际机场、滨海湾和圣淘沙综合度假村的建设项目中。'
singapore: '新加坡'
malaysia: '马来西亚'
email: '电子邮件'
phone: '电话'
fax: '传真'
no_articles: '没有文章可用。'
back_to_articles: '返回文章'
distributor_title: '成为分销商'
distributor_partner_title: '与世界品牌粘合剂合作'
distributor_partner_description: '加入我们值得信赖的全球分销商网络，将高性能粘合剂带到您的市场。'
distributor_apply_now: '立即申请'
distributor_why_partner: '为什么与我们合作'
distributor_reliable_quality_title: '可靠的质量'
distributor_reliable_quality_description: '凭借在粘合剂制造领域数十年的经验和持续的产品创新作为后盾。'
distributor_eco_title: '环保配方'
distributor_eco_description: '我们提供无甲醛粘合剂和环保型溶剂型解决方案，这些解决方案干燥迅速，同时符合全球安全标准。'
distributor_brand_title: '品牌和技术支持'
distributor_brand_description: '获得营销工具、技术培训、安全数据表以及我们产品专家的指导。'
distributor_attractive_margins_title: '有吸引力的利润'
distributor_attractive_margins_description: '我们提供具有竞争力的定价结构和根据您的市场量身定制的分销商计划。'
distributor_apply_title: '申请成为分销商'
distributor_apply_description: '请填写以下表格。我们将在 5 个工作日内回复您。'
distributor_company_name: '公司名称*'
distributor_contact_name: '联系人姓名*'
distributor_website_url: '网址'
distributor_job_title: '职称'
distributor_city_region: '城市/地区'
distributor_phone_number: '电话号码'
distributor_industries: '行业或市场细分？'
distributor_product_categories: '产品类别'
distributor_water_based: '水性粘合剂'
distributor_formaldehyde_free: '无甲醛粘合剂'
distributor_eco_friendly: '环保粘合剂'
distributor_construction: '建筑粘合剂'
distributor_others: '其他'
distributor_interest: '您的兴趣或评论'
distributor_submit: '提交申请'