lang_name: '中文'
title: '地球牌粘合剂制造商'
home: '首页'
products: '产品'
about_us: '关于我们'
articles: '文章'
contact: '联系我们'
slide1_h1: '环保'
slide1_p: '低毒性和低甲醛排放的绿色标签认证。使用我们的粘合剂获得BCA绿色建筑标志积分。'
slide2_h1: '地板'
slide2_p: '适用于所有地板应用的粘合剂。硬木和乙烯基地板、地毯和瓷砖。'
slide3_h1: '一般木工'
slide3_p: '适用于家具制作的粘合剂。'
slide4_h1: '全球出口'
slide4_p: '联系我们成为经销商。我们将产品运送到全球各地。'
pitch1_h3: 'ISO 14001'
pitch1: '我们的粘合剂符合国际质量标准。'
pitch2_h3: '环保'
pitch2: '绿色标签认证的低毒性和低甲醛排放粘合剂。'
pitch3_h3: '耐用'
pitch3: '持久的强力粘合。'
pitch4_h3: '全球'
pitch4: '我们将粘合剂出口到全球各地。'
references_h6: '使用我们产品的项目。'
company: '公司'
company_p1: '我们是东南亚领先的粘合剂制造商和分销商，总部设在新加坡。公司成立于1972年，已通过ISO 14001认证，展示了我们对研发、产品质量和细致客户服务的重视。'
company_p2: '我们的产品广泛应用于各种行业，尤其是在樟宜国际机场、滨海湾和圣淘沙综合度假村的建设项目中。'
singapore: '新加坡'
malaysia: '马来西亚'
email: '电子邮件'
phone: '电话'
fax: '传真'

