available_in: "供应于"
technical_specification: "技术规格"
msds: "材料安全数据表"
products_200_description: "用于聚氨酯泡沫和地毯的接触型胶粘剂。"
products_300_description: "用于橡胶、金属、木材、皮革、塑料、硬板等的接触型胶粘剂。"
products_3000_description: "一种优质的合成橡胶。超强、柔韧、防水且耐化学性。可粘附于木材和橡胶等天然表面。也可粘附于人造皮革、橡胶化织物、玻璃金属、陶瓷、硬板、油毡、硬塑料和混凝土。"
products_3008-pva_description: "用于一般木工的快速干燥水基胶粘剂。"
products_3009-pva_description: "用于拼花地板的水基胶粘剂。"
products_3013_description: "用于难粘表面的水基胶粘剂。"
products_303-superglue_description: "用于金属、塑料、橡胶等的氰基丙烯酸酯胶粘剂。"
products_303-vinyl-tile_description: "用于乙烯基地板的胶粘剂。"
products_313-pva_description: "用于一般木工的水基胶粘剂。"
products_323-pva_description: "用于一般用途的基胶粘剂。"
products_500_description: "用于帆布、橡胶、金属、皮革、塑料、木材、硬板等的接触型胶粘剂。"
products_600_description: "用于橡胶、金属、胶合板、皮革、塑料、黄色泡沫、铝等的非易燃喷胶。"
products_606-vinyl-tile_description: "用于乙烯基地板、墙面覆盖物和PVC背衬地毯的胶粘剂。"
products_800_description: "用于聚氨酯泡沫、玻璃纤维和木材的中等粘度喷胶。"
products_808_description: "一种优质的合成橡胶。柔韧、防水且耐化学性。适用于人造皮革、皮膜材料、织物、硫化橡胶、木材、玻璃金属、陶瓷、硬板、油毡、混凝土和硬塑料。"
products_8830_description: "无味的聚苯乙烯泡沫接触型胶粘剂。"
products_909_description: "用于粘合大多数类型的纺织品和PVC背衬地毯的压敏胶粘剂。"
products_acetic-silicone-sealants_description: "用于一般玻璃安装和各种DIY用途的硅胶。"
products_acrylic-sealants_description: "用于一般玻璃安装和各种DIY应用的丙烯酸密封胶。"
products_E-100_description: "用于橡胶、金属、木材、皮革、塑料、硬板的胶粘剂。适用于家具、室内装饰、皮革、空调和制鞋行业。"
products_g-spray_description: "耐热喷胶，用于聚氨酯泡沫、玻璃纤维和木材。"
products_high-g-spray_description: "用于聚氨酯泡沫、玻璃纤维和木材的耐热喷胶。"
products_PVC-solvent-cement_description: "用于PVC管道、配件、水管等行业的胶粘剂。"
products_world-bond_description: "一种可用于粘合多种建筑材料的枪式接触型胶粘剂。"

